#!/bin/bash

self="$(basename "$0")"

if [[ "${self}" == "peg-gcc-4.7.2" ]]; then
	the_gcc="gcc"
elif [[ "${self}" == "peg-g++-4.1.3" ]]; then
	export C_INCLUDE_PATH=/usr/include/i386-linux-gnu
	export CPLUS_INCLUDE_PATH=/usr/include/i386-linux-gnu
	export LIBRARY_PATH=/usr/lib/i386-linux-gnu
	the_gcc="g++-4.1"
elif [[ "${self}" == "peg-g++-4.9.1" ]]; then
	the_gcc="g++-4.9"
else
	echo "Bad compiler '$0' requested" >2
	exit 1
fi

shift
cmd="$*"
sudo -E /usr/sbin/chroot "/opt/jail" sh -c "cd $PWD; ${the_gcc} ${cmd}"
